# Imports

In [82]:
import requests
from bs4 import BeautifulSoup
import pandas
import unicodedata

# Constants

In [ ]:
base_url = 'https://mibici.net'

# Fetch website

In [ ]:
source_url = f'{base_url}/es/datos-abiertos/'

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
}

In [13]:
r = requests.get(source_url, headers=headers)

r

In [14]:
r.text

'<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="INDEX,FOLLOW"/><title>Mi Bici | Datos abiertos</title><meta name="description" content="Explora, experimenta y comparte los datos de uso de Mi Bici."><link rel="canonical" href="https://mibici.net/es/datos-abiertos/"><meta property="og:title" content="MiBici |Datos abiertos"><meta property="og:description" content="Explora, experimenta y comparte los datos de uso de Mi Bici."><meta property="og:image" content="https://www.mibici.net/site/templates/assets/images/og-meta-image.jpg"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:width" content="960"><meta property="og:image:height" content="540"><meta property="og:type" content="website"><meta property="og:site_name" content="Mi Bici"><meta property="og:url" content="https://mibici.net/es/datos-abiertos/"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="MiBiciPublica"><meta name="twitter:creator" content="MiBiciPublica"><script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "BreadcrumbList",\n  "itemListElement": [\n  {\n    "@type": "ListItem",\n    "position": 1,\n    "name": "Datos abiertos",\n    "item": "https://mibici.net/es/datos-abiertos/"\n  }\n  ]\n}\n</script><meta name="generator" content="ProcessWire"><link rel="alternate" href="https://mibici.net/es/datos-abiertos/" hreflang="es"><link rel="alternate" href="https://mibici.net/es/datos-abiertos/" hreflang="x-default"><link rel="alternate" href="https://mibici.net/en/open-data/" hreflang="english"><link rel="apple-touch-icon" sizes="180x180" href="/site/templates/favicon/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/site/templates/favicon/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/site/templates/favicon/favicon-16x16.png"><link rel="manifest" href="/site/templates/favicon/site.webmanifest?v=1.1"><link rel="mask-icon" href="/site/templates/favicon/safari-pinned-tab.svg" color="#00953a"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/><meta name="apple-mobile-web-app-title" content="Mi Bici"><meta name="application-name" content="Mi Bici"><meta name="msapplication-TileColor" content="#fdc820"><meta name="theme-color" content="#fdc820"><script async src="https://www.googletagmanager.com/gtag/js?id=G-ET9N09G12L"></script><script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n  gtag(\'config\', \'G-ET9N09G12L\');\n</script><link rel="stylesheet" type="text/css" href="https://unpkg.com/aos@next/dist/aos.css" /><link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css" integrity="sha256-K3Njjl2oe0gjRteXwX01fQD5fkk9JFFBdUHy/h38ggY=" crossorigin="anonymous" rel="stylesheet"><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.css"><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Roboto:wght@400;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="/site/assets/aiom/css_b44a11908d069e48b4dd6b86f51a7826.css"><link rel="stylesheet" type="text/css" href="/site/templates/assets/scripts/loading.css"><link rel="stylesheet" type="text/css" href="/site/templates/assets/scripts/wink.css?v=0.12"><style>\n    * {\n      letter-spacing: 0 !important;\n    }\n    .grecaptcha-badge {\n      width: 70px !important;\n      overflow: hidden !important;\n      transition: all 0.3s ease !important;\n      left: 4px !important;\n    }\n    .grecaptcha-badge:hover {\n      width: 256px !important;\n    }\n  </style></head><body ><div class="header-container"><header class="main-nav"><div class="container"><a href="/"><img class="logo" src="/site/templates/assets/images/logo-mibici-obscuro.svg" alt="Mi Bici"></a></div><div class="container nav-resp"><nav><ul><li><a href="/es/mapa/" title="Mapa">\n                  Mapa                </a></li><li class="space-vr">|</li><li><a href="/es/preguntas-frecuentes/" title="Preguntas frecuentes">\n                 Preguntas frecuentes               </a></li><li class="space-vr">|</li><li><a href="/es/como-funciona/" title="¿Cómo funciona?">\n                 ¿Cómo funciona?               </a></li><li class="space-vr">|</li><li><a href="/es/contacto/" rel="noreferrer" title="Contacto">\n                 Contacto               </a></li><li class="visible-movil"><a href="/es/iniciar-sesion/" title="Iniciar Sesión" rel="noreferrer"><button class="btn-outline">Iniciar Sesión</button></a></li><li class="visible-movil"><a href="/es/registro/" title="Registro" rel="noreferrer"><button type="button" name="button">\n                   Suscríbete                 </button></a></li></ul></nav><div id="nav-icon"><span></span><span></span><span></span></div></div><div class="container-cta"><a href="/es/iniciar-sesion/" title="Iniciar Sesión" rel="noreferrer"><button class="btn-outline">Iniciar Sesión</button></a><a href="/es/tarifas/" title="Tarifas" rel="noreferrer" ><button type="button" name="button">\n                Suscríbete              </button></a></div></header></div><div class="j-workspace "><div class="j-wrap"><h1 class="m-t-m">Datos abiertos</h1><p> ¡Explora, experimenta y comparte los datos de uso de Mi Bici!</p></div><section class="open-data j-wrap-80 "><div class="grid"><div class="unit half" align="center"><div class="head-data"><svg width="42" height="41" viewBox="0 0 42 41" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M28.49 40.27C23.1 40.27 18.49 36.37 18.49 31.04V9.94997C18.49 7.64997 16.47 5.98997 13.88 5.98997C11.4 5.98997 9.27 7.51997 9.27 9.94997V19.84H4V9.94997C4 4.61997 8.39 0.719971 13.77 0.719971C19.31 0.719971 23.77 4.70997 23.77 9.94997V31.04C23.77 33.46 26.01 34.99 28.5 34.99C30.98 34.99 33 33.46 33 31.04V19.84H38.27V31.04C38.27 36.37 33.88 40.27 28.49 40.27Z" fill="#FED925"/><path d="M40.9003 19.18C40.9003 22.09 38.5403 24.45 35.6303 24.45C32.7203 24.45 30.3604 22.09 30.3604 19.18C30.3604 16.27 32.7203 13.91 35.6303 13.91C38.5403 13.91 40.9003 16.27 40.9003 19.18Z" fill="#FED925"/><path d="M11.9004 19.18C11.9004 22.09 9.54035 24.45 6.63035 24.45C3.72035 24.45 1.36035 22.09 1.36035 19.18C1.36035 16.27 3.72035 13.91 6.63035 13.91C9.54035 13.91 11.9004 16.27 11.9004 19.18Z" fill="#FED925"/><path d="M9.80047 19.1799C9.80047 20.9299 8.38046 22.3399 6.64046 22.3399C4.89046 22.3399 3.48047 20.9199 3.48047 19.1799C3.48047 17.4299 4.90046 16.0199 6.64046 16.0199C8.38046 16.0099 9.80047 17.4299 9.80047 19.1799Z" fill="#FFF7D4"/><path d="M38.8005 19.1799C38.8005 20.9299 37.3805 22.3399 35.6405 22.3399C33.8905 22.3399 32.4805 20.9199 32.4805 19.1799C32.4805 17.4299 33.9005 16.0199 35.6405 16.0199C37.3805 16.0099 38.8005 17.4299 38.8005 19.1799Z" fill="#FFF7D4"/><path d="M12.9004 11.89C12.9004 8.43 10.0903 5.63 6.63035 5.63C3.17035 5.63 0.360352 8.43 0.360352 11.89C0.360352 13.33 0.850355 14.66 1.66035 15.71C1.83035 15.98 2.04035 16.24 2.28035 16.47L6.06035 20.25C6.37035 20.56 6.88035 20.56 7.19035 20.25L10.9704 16.47C11.2104 16.23 11.4104 15.98 11.5804 15.71C12.4104 14.66 12.9004 13.33 12.9004 11.89Z" fill="#00953B"/><path d="M2.29004 11.8C2.29004 14.2 4.24004 16.15 6.64004 16.15C9.04004 16.15 10.99 14.2 10.99 11.8C10.99 9.39995 9.04004 7.44995 6.64004 7.44995C4.23004 7.45995 2.29004 9.39995 2.29004 11.8Z" fill="#FFF7D4"/><path d="M41.9003 11.89C41.9003 8.43 39.0903 5.63 35.6303 5.63C32.1703 5.63 29.3604 8.43 29.3604 11.89C29.3604 13.33 29.8504 14.66 30.6604 15.71C30.8304 15.98 31.0403 16.24 31.2803 16.47L35.0603 20.25C35.3703 20.56 35.8804 20.56 36.1904 20.25L39.9704 16.47C40.2104 16.23 40.4104 15.98 40.5804 15.71C41.4104 14.66 41.9003 13.33 41.9003 11.89Z" fill="#00953B"/><path d="M31.29 11.8C31.29 14.2 33.24 16.15 35.64 16.15C38.04 16.15 39.99 14.2 39.99 11.8C39.99 9.39995 38.04 7.44995 35.64 7.44995C33.23 7.45995 31.29 9.39995 31.29 11.8Z" fill="white"/></svg><h2> Total de viajes realizados.</h2></div><div class="body-data"><p class="xl" id="trips">\n              39,437,863            </p></div></div><div class="unit half" align="center"><div class="head-data"><svg width="40" height="auto" viewBox="0 0 52 39" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22.7202 27.61L16.4601 30.74C15.0001 31.47 13.2802 31.47 11.8202 30.74L5.56015 27.61C2.85015 27.61 0.660156 29.81 0.660156 32.51V38.64H27.6302V32.51C27.6202 29.81 25.4202 27.61 22.7202 27.61Z" fill="#00953B"/><path d="M3.79969 9.06C2.75969 11.83 2.8797 14.9 4.1297 17.58C5.3797 20.26 7.65971 22.32 10.4497 23.3V23.94C10.4497 26.65 8.24969 27.62 5.54969 27.62L11.8097 30.75C13.2697 31.48 14.9897 31.48 16.4597 30.75L22.7197 27.62C20.0097 27.62 17.8197 26.65 17.8197 23.94V23.3C22.3497 21.7 25.3297 17.36 25.1797 12.55C25.1697 12.26 25.1897 11.97 25.1597 11.68H10.4697C7.9897 11.68 5.60969 10.74 3.79969 9.06Z" fill="#FFED00"/><path d="M3.79978 9.06C5.60978 10.74 7.9798 11.68 10.4498 11.68H25.1398C25.1498 9.08 24.1198 6.59 22.2798 4.75C20.4398 2.91 17.9498 1.88 15.3598 1.87H6.66981C2.93981 1.87 1.01978 6.46 3.73978 9.01L3.79978 9.06Z" fill="#7B868C"/><path d="M3.79978 9.06C5.60978 10.74 7.9798 11.68 10.4498 11.68H25.1398C25.1498 9.08 24.1198 6.59 22.2798 4.75C20.4398 2.91 17.9498 1.88 15.3598 1.87H6.66981C2.93981 1.87 1.01978 6.46 3.73978 9.01L3.79978 9.06Z" stroke="#7B868C" stroke-width="2" stroke-miterlimit="10"/><path d="M46.6 27.48L40.34 30.61C38.88 31.34 37.16 31.34 35.7 30.61L29.44 27.48C26.73 27.48 24.54 29.68 24.54 32.38V38.51H51.51V32.38C51.5 29.67 49.31 27.48 46.6 27.48Z" fill="#00953B"/><path d="M45.9205 4.50997C44.0805 2.66997 41.5904 1.64997 38.9904 1.64997H37.0405C34.4405 1.63997 31.9504 2.66997 30.1104 4.50997C28.2704 6.34997 27.2305 8.83997 27.2305 11.44V24.4C27.2305 25.37 28.0204 26.16 28.9904 26.16H47.0405C48.0105 26.16 48.8004 25.37 48.8004 24.4V11.43C48.8004 8.83997 47.7605 6.33997 45.9205 4.50997Z" fill="#7B868C"/><path d="M45.9205 4.50997C44.0805 2.66997 41.5904 1.64997 38.9904 1.64997H37.0405C34.4405 1.63997 31.9504 2.66997 30.1104 4.50997C28.2704 6.34997 27.2305 8.83997 27.2305 11.44V24.4C27.2305 25.37 28.0204 26.16 28.9904 26.16H47.0405C48.0105 26.16 48.8004 25.37 48.8004 24.4V11.43C48.8004 8.83997 47.7605 6.33997 45.9205 4.50997Z" stroke="#7B868C" stroke-width="2" stroke-miterlimit="10"/><path d="M27.6903 8.91998C26.6503 11.69 26.7703 14.76 28.0203 17.44C29.2703 20.12 31.5503 22.18 34.3403 23.16V23.8C34.3403 26.51 32.1403 27.48 29.4403 27.48L35.7003 30.61C37.1603 31.34 38.8803 31.34 40.3503 30.61L46.6103 27.48C43.9003 27.48 41.7103 26.51 41.7103 23.8V23.16C46.2403 21.56 49.2203 17.22 49.0703 12.41C49.0603 12.12 49.0803 11.83 49.0503 11.54H34.3603C31.8703 11.54 29.4903 10.61 27.6903 8.91998Z" fill="#FFED00"/><path d="M29.0005 34.44C30.2505 35.8 32.0105 36.57 33.8505 36.57V26.64C33.8505 24.89 33.1505 23.21 31.9105 21.97C30.6705 20.73 28.9905 20.04 27.2305 20.04V29.95C27.2405 31.62 27.8705 33.22 29.0005 34.44Z" fill="#7B868C"/><path d="M29.0005 34.44C30.2505 35.8 32.0105 36.57 33.8505 36.57V26.64C33.8505 24.89 33.1505 23.21 31.9105 21.97C30.6705 20.73 28.9905 20.04 27.2305 20.04V29.95C27.2405 31.62 27.8705 33.22 29.0005 34.44Z" stroke="#7B868C" stroke-width="2" stroke-miterlimit="10"/><path d="M47.0299 34.44C48.1599 33.22 48.7899 31.62 48.7899 29.95V20.04C47.0399 20.04 45.3499 20.73 44.1099 21.97C42.8699 23.21 42.1699 24.89 42.1699 26.64V36.57C44.0199 36.57 45.7799 35.8 47.0299 34.44Z" fill="#7B868C"/><path d="M47.0299 34.44C48.1599 33.22 48.7899 31.62 48.7899 29.95V20.04C47.0399 20.04 45.3499 20.73 44.1099 21.97C42.8699 23.21 42.1699 24.89 42.1699 26.64V36.57C44.0199 36.57 45.7799 35.8 47.0299 34.44Z" stroke="#7B868C" stroke-width="2" stroke-miterlimit="10"/><path d="M48.9898 13.3C48.9898 19.36 44.0798 24.27 38.0198 24.27C31.9598 24.27 27.0498 19.36 27.0498 13.3C27.0498 7.23997 31.9598 2.32997 38.0198 2.32997C44.0798 2.31997 48.9898 7.23997 48.9898 13.3Z" fill="#FFED00"/><path d="M45.9205 4.55001C44.0805 2.71001 41.5904 1.69001 38.9904 1.69001H37.0405C34.4405 1.68001 31.9504 2.71001 30.1104 4.55001C28.2704 6.39001 27.2305 8.88001 27.2305 11.48V10.97C27.2305 11.94 28.0204 12.73 28.9904 12.73H47.0405C48.0105 12.73 48.8004 11.94 48.8004 10.97V11.48C48.8004 8.88001 47.7605 6.39001 45.9205 4.55001Z" fill="#7B868C"/><path d="M45.9205 4.55001C44.0805 2.71001 41.5904 1.69001 38.9904 1.69001H37.0405C34.4405 1.68001 31.9504 2.71001 30.1104 4.55001C28.2704 6.39001 27.2305 8.88001 27.2305 11.48V10.97C27.2305 11.94 28.0204 12.73 28.9904 12.73H47.0405C48.0105 12.73 48.8004 11.94 48.8004 10.97V11.48C48.8004 8.88001 47.7605 6.39001 45.9205 4.55001Z" stroke="#7B868C" stroke-width="2" stroke-miterlimit="10"/></svg><h2> Registros totales</h2></div><div class="body-data"><p class="xl" id="users">\n              221,956            </p></div></div></div></section><section class="j-wrap-80 open-data"><div class="data-widget"><h2>Gestor de datos</h2><p>Conoce cómo se mueve Mi Bici, qué estaciones son más ó menos utilizadas, horario con más demanda, la cantidad de viajes y muchos más datos con la siguiente herramienta.</p><p>Indicaciones:</p><div class="grid"><div class="unit half"><ul><li><img src="/site/templates/static/455375-1515453811/images/open-contraer.svg" alt="Contrae información de manera general.">\n                 Contrae información de manera general.              </li><li><img src="/site/templates/static/455375-1515453811/images/open-desdoblar.svg" alt="Desdobla información de manera agrupada.">\n                 Desdobla información de manera agrupada.              </li><li><img src="/site/templates/static/455375-1515453811/images/open-desdoblar-desagrupado.svg" alt="Desdobla información de manera desagrupada.">\n                 Desdobla información de manera desagrupada.              </li></ul></div><div class="unit half"><ul><li><img src="/site/templates/static/455375-1515453811/images/open-desdoblar-particular.svg" alt="Desdobla información de manera particular.">\n                 Desdobla información de manera particular.              </li><li><img src="/site/templates/static/455375-1515453811/images/open-boton-activado.svg" alt="Botón activado.">\n                 Botón activado.              </li></ul></div></div><p><a href="/site/assets/files/1118/nomenclatura_2026_09.csv"> Manual para uso de datos abiertos. </a></p></div><iframe class="power-bi-desktop" width="933" height="700" src="https://app.powerbi.com/view?r=eyJrIjoiODcwMGQyZTMtZWM2MS00OTA2LTgzYWYtZWU4YjEyMDhkOGI3IiwidCI6ImVjMDM2YWU0LWM4ZTMtNGM3ZC05YTFmLWFhYWRjZWI3ZTBkNSJ9" frameborder="0" allowFullScreen="true"></iframe><iframe class="power-bi-mobile" width="100%" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiODcwMGQyZTMtZWM2MS00OTA2LTgzYWYtZWU4YjEyMDhkOGI3IiwidCI6ImVjMDM2YWU0LWM4ZTMtNGM3ZC05YTFmLWFhYWRjZWI3ZTBkNSJ9" frameborder="0" allowFullScreen="true"></iframe></section><section class="j-wrap-80"><h2>Descargas</h2><p> Accede a la información en formato .CSV clasificada por mes y por año.</p><section class="data-year-container"><dl class="open-dl" onclick="showAnsw(\'0\');"><dt>\n            2014           </dt><div id="answ-0" class="grid open-badge-container"><div class="unit one-quarter"><ul><a href="/site/assets/files/1079/datos_abiertos_2014_12.csv"><li>Diciembre</li></a></div></dl><dl class="open-dl" onclick="showAnsw(\'1\');"><dt>\n            2015           </dt><div id="answ-1" class="grid open-badge-container"><div class="unit one-quarter"><ul><a href="/site/assets/files/1084/datos_abiertos_2015_01.csv"><li>Enero</li></a><a href="/site/assets/files/1097/datos_abiertos_2015_02.csv"><li>Febrero</li></a><a href="/site/assets/files/1098/datos_abiertos_2015_03.csv"><li>Marzo</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1099/datos_abiertos_2015_04.csv"><li>Abril</li></a><a href="/site/assets/files/1100/datos_abiertos_2015_05.csv"><li>Mayo</li></a><a href="/site/assets/files/1101/datos_abiertos_2015_06.csv"><li>Junio</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1102/datos_abiertos_2015_07.csv"><li>Julio</li></a><a href="/site/assets/files/1103/datos_abiertos_2015_08.csv"><li>Agosto</li></a><a href="/site/assets/files/1104/datos_abiertos_2015_09.csv"><li>Septiembre</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1105/datos_abiertos_2015_10.csv"><li>Octubre</li></a><a href="/site/assets/files/1106/datos_abiertos_2015_11.csv"><li>Noviembre</li></a><a href="/site/assets/files/1107/datos_abiertos_2015_12.csv"><li>Diciembre</li></a></ul></div></div></dl><dl class="open-dl" onclick="showAnsw(\'2\');"><dt>\n            2016           </dt><div id="answ-2" class="grid open-badge-container"><div class="unit one-quarter"><ul><a href="/site/assets/files/1020/datos_abiertos_2016_01-1.csv"><li>Enero</li></a><a href="/site/assets/files/1021/datos_abiertos_2016_02.csv"><li>Febrero</li></a><a href="/site/assets/files/1023/datos_abiertos_2016_03.csv"><li>Marzo</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1029/datos_abiertos_2016_04.csv"><li>Abril</li></a><a href="/site/assets/files/1058/datos_abiertos_2016_05.csv"><li>Mayo</li></a><a href="/site/assets/files/1080/datos_abiertos_2016_06.csv"><li>Junio</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1081/datos_abiertos_2016_07.csv"><li>Julio</li></a><a href="/site/assets/files/1082/datos_abiertos_2016_08.csv"><li>Agosto</li></a><a href="/site/assets/files/1083/datos_abiertos_2016_09.csv"><li>Septiembre</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1108/datos_abiertos_2016_10.csv"><li>Octubre</li></a><a href="/site/assets/files/1109/datos_abiertos_2016_11.csv"><li>Noviembre</li></a><a href="/site/assets/files/1110/datos_abiertos_2016_12.csv"><li>Diciembre</li></a></ul></div></div></dl><dl class="open-dl" onclick="showAnsw(\'3\');"><dt>\n            2017           </dt><div id="answ-3" class="grid open-badge-container"><div class="unit one-quarter"><ul><a href="/site/assets/files/1022/datos_abiertos_2017_01.csv"><li>Enero</li></a><a href="/site/assets/files/1111/datos_abiertos_2017_02.csv"><li>Febrero</li></a><a href="/site/assets/files/1112/datos_abiertos_2017_03.csv"><li>Marzo</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1115/datos_abiertos_2017_04-1.csv"><li>Abril</li></a><a href="/site/assets/files/1116/datos_abiertos_2017_05.csv"><li>Mayo</li></a><a href="/site/assets/files/1119/datos_abiertos_2017_06.csv"><li>Junio</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1120/datos_abiertos_2017_07.csv"><li>Julio</li></a><a href="/site/assets/files/1122/datos_abiertos_2017_08.csv"><li>Agosto</li></a><a href="/site/assets/files/1123/datos_abiertos_2017_09.csv"><li>Septiembre</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site/assets/files/1124/datos_abiertos_2017_10.csv"><li>Octubre</li></a><a href="/site/assets/files/1197/datos_abiertos_2017_11.csv"><li>Noviembre</li></a><a href="/site/assets/files/1198/datos_abiertos_2017_12.csv"><li>Diciembre</li></a></ul></div></div></dl><dl class="open-dl" onclick="showAnsw(\'4\');"><dt>\n            2018           </dt><div id="answ-4" class="grid open-badge-container"><div class="unit one-quarter"><ul><a href="/site/assets/files/1200/datos_abiertos_2018_01.csv"><li>Enero</li></a><a href="/site/assets/files/1201/datos_abiertos_2018_02.csv"><li>Febrero</li></a><a href="/site/assets/files/1202/datos_abiertos_2018_03.csv"><li>Marzo</li></a></ul></div><div class="unit one-quarter"><ul><a href="/site

# Parse HTML for file links

In [16]:
soup = BeautifulSoup(r.text, 'html.parser')

In [ ]:
links = soup.find_all('a')

In [34]:
parent_dir = '/site/assets/files'

file_links = []
file_paths = []

for link in links:
    link_href = link.get('href')
    if not link_href.startswith(parent_dir): continue
    if not 'datos_abiertos' in link_href: continue
    file_links.append(link)
    file_paths.append(link_href)

# file_links = [link for link in links if link.get('href').startswith(parent_dir) and ('datos_abiertos' in link.get('href'))]
# links[10].get('href')

# Filter by date range

In [62]:
df_paths = pandas.DataFrame(file_paths, columns=['path'])

df_paths.head()

                                                path
0  /site/assets/files/1079/datos_abiertos_2014_12...
1  /site/assets/files/1084/datos_abiertos_2015_01...
2  /site/assets/files/1097/datos_abiertos_2015_02...
3  /site/assets/files/1098/datos_abiertos_2015_03...
4  /site/assets/files/1099/datos_abiertos_2015_04...

In [63]:
df_date = ( df_paths.path
    .str.extract(r'(\d{4}_\d{2})')
    .rename(columns={0:'file_date'})
)

df_date.head()

  file_date
0   2014_12
1   2015_01
2   2015_02
3   2015_03
4   2015_04

In [64]:
df_paths['file_date'] = pandas.to_datetime(df_date['file_date'], format='%Y_%m')

df_paths.head()

                                                path  file_date
0  /site/assets/files/1079/datos_abiertos_2014_12... 2014-12-01
1  /site/assets/files/1084/datos_abiertos_2015_01... 2015-01-01
2  /site/assets/files/1097/datos_abiertos_2015_02... 2015-02-01
3  /site/assets/files/1098/datos_abiertos_2015_03... 2015-03-01
4  /site/assets/files/1099/datos_abiertos_2015_04... 2015-04-01

In [66]:
date_start = '2016-04-01'
date_end = '2016-10-01'
df_paths.query('(file_date >= @date_start) and (file_date <= @date_end)')

                                                 path  file_date
16  /site/assets/files/1029/datos_abiertos_2016_04... 2016-04-01
17  /site/assets/files/1058/datos_abiertos_2016_05... 2016-05-01
18  /site/assets/files/1080/datos_abiertos_2016_06... 2016-06-01
19  /site/assets/files/1081/datos_abiertos_2016_07... 2016-07-01
20  /site/assets/files/1082/datos_abiertos_2016_08... 2016-08-01
21  /site/assets/files/1083/datos_abiertos_2016_09... 2016-09-01
22  /site/assets/files/1108/datos_abiertos_2016_10... 2016-10-01

In [80]:
df_paths.path.to_list()

['/site/assets/files/1079/datos_abiertos_2014_12.csv',
 '/site/assets/files/1084/datos_abiertos_2015_01.csv',
 '/site/assets/files/1097/datos_abiertos_2015_02.csv',
 '/site/assets/files/1098/datos_abiertos_2015_03.csv',
 '/site/assets/files/1099/datos_abiertos_2015_04.csv',
 '/site/assets/files/1100/datos_abiertos_2015_05.csv',
 '/site/assets/files/1101/datos_abiertos_2015_06.csv',
 '/site/assets/files/1102/datos_abiertos_2015_07.csv',
 '/site/assets/files/1103/datos_abiertos_2015_08.csv',
 '/site/assets/files/1104/datos_abiertos_2015_09.csv',
 '/site/assets/files/1105/datos_abiertos_2015_10.csv',
 '/site/assets/files/1106/datos_abiertos_2015_11.csv',
 '/site/assets/files/1107/datos_abiertos_2015_12.csv',
 '/site/assets/files/1020/datos_abiertos_2016_01-1.csv',
 '/site/assets/files/1021/datos_abiertos_2016_02.csv',
 '/site/assets/files/1023/datos_abiertos_2016_03.csv',
 '/site/assets/files/1029/datos_abiertos_2016_04.csv',
 '/site/assets/files/1058/datos_abiertos_2016_05.csv',
 '/site/assets/files/1080/datos_abiertos_2016_06.csv',
 '/site/assets/files/1081/datos_abiertos_2016_07.csv',
 '/site/assets/files/1082/datos_abiertos_2016_08.csv',
 '/site/assets/files/1083/datos_abiertos_2016_09.csv',
 '/site/assets/files/1108/datos_abiertos_2016_10.csv',
 '/site/assets/files/1109/datos_abiertos_2016_11.csv',
 '/site/assets/files/1110/datos_abiertos_2016_12.csv',
 '/site/assets/files/1022/datos_abiertos_2017_01.csv',
 '/site/assets/files/1111/datos_abiertos_2017_02.csv',
 '/site/assets/files/1112/datos_abiertos_2017_03.csv',
 '/site/assets/files/1115/datos_abiertos_2017_04-1.csv',
 '/site/assets/files/1116/datos_abiertos_2017_05.csv',
 '/site/assets/files/1119/datos_abiertos_2017_06.csv',
 '/site/assets/files/1120/datos_abiertos_2017_07.csv',
 '/site/assets/files/1122/datos_abiertos_2017_08.csv',
 '/site/assets/files/1123/datos_abiertos_2017_09.csv',
 '/site/assets/files/1124/datos_abiertos_2017_10.csv',
 '/site/assets/files/1197/datos_abiertos_2017_11.csv',
 '/site/assets/files/1198/datos_abiertos_2017_12.csv',
 '/site/assets/files/1200/datos_abiertos_2018_01.csv',
 '/site/assets/files/1201/datos_abiertos_2018_02.csv',
 '/site/assets/files/1202/datos_abiertos_2018_03.csv',
 '/site/assets/files/1203/datos_abiertos_2018_04.csv',
 '/site/assets/files/1204/datos_abiertos_2018_05.csv',
 '/site/assets/files/1205/datos_abiertos_2018_06.csv',
 '/site/assets/files/1206/datos_abiertos_2018_07.csv',
 '/site/assets/files/1207/datos_abiertos_2018_08.csv',
 '/site/assets/files/1208/datos_abiertos_2018_09.csv',
 '/site/assets/files/1209/datos_abiertos_2018_10.csv',
 '/site/assets/files/1210/datos_abiertos_2018_11.csv',
 '/site/assets/files/1211/datos_abiertos_2018_12.csv',
 '/site/assets/files/1214/datos_abiertos_2019_01.csv',
 '/site/assets/files/1217/datos_abiertos_2019_02.csv',
 '/site/assets/files/1218/datos_abiertos_2019_03.csv',
 '/site/assets/files/1219/datos_abiertos_2019_04.csv',
 '/site/assets/files/1220/datos_abiertos_2019_05.csv',
 '/site/assets/files/1221/datos_abiertos_2019_06.csv',
 '/site/assets/files/1222/datos_abiertos_2019_07.csv',
 '/site/assets/files/1223/datos_abiertos_2019_08.csv',
 '/site/assets/files/1224/datos_abiertos_2019_09.csv',
 '/site/assets/files/1225/datos_abiertos_2019_10.csv',
 '/site/assets/files/1227/datos_abiertos_2019_11.csv',
 '/site/assets/files/1228/datos_abiertos_2019_12.csv',
 '/site/assets/files/1230/datos_abiertos_2020_01.csv',
 '/site/assets/files/1231/datos_abiertos_2020_02.csv',
 '/site/assets/files/1232/datos_abiertos_2020_03.csv',
 '/site/assets/files/1235/datos_abiertos_2020_04.csv',
 '/site/assets/files/1236/datos_abiertos_2020_05.csv',
 '/site/assets/files/1237/datos_abiertos_2020_06.csv',
 '/site/assets/files/1238/datos_abiertos_2020_07.csv',
 '/site/assets/files/1239/datos_abiertos_2020_08.csv',
 '/site/assets/files/1240/datos_abiertos_2020_09.csv',
 '/site/assets/files/1241/datos_abiertos_2020_10.csv',
 '/site/assets/files/1317/datos_abiertos_2020_11.csv',
 '/site/assets/files/1318/datos_abiertos_2020_12.csv',
 '/site/assets/files/1320/datos_abiertos_2021_01.csv',
 '/site/assets/files/1323/datos_abiertos_2021_02.csv',
 '/site/assets/files/1322/datos_abiertos_2021_03.csv',
 '/site/assets/files/2129/datos_abiertos_2021_04.csv',
 '/site/assets/files/3292/datos_abiertos_2021_05.csv',
 '/site/assets/files/4572/datos_abiertos_2021_06.csv',
 '/site/assets/files/5728/datos_abiertos_2021_07.csv',
 '/site/assets/files/7073/datos_abiertos_2021_08.csv',
 '/site/assets/files/8461/datos_abiertos_2021_09.csv',
 '/site/assets/files/10088/datos_abiertos_2021_10.csv',
 '/site/assets/files/11538/datos_abiertos_2021_11.csv',
 '/site/assets/files/12780/datos_abiertos_2021_12.csv',
 '/site/assets/files/14797/datos_abiertos_2022_01.csv',
 '/site/assets/files/16831/datos_abiertos_2022_02.csv',
 '/site/assets/files/19034/datos_abiertos_2022_03.csv',
 '/site/assets/files/20338/datos_abiertos_2022_04.csv',
 '/site/assets/files/21842/datos_abiertos_2022_05.csv',
 '/site/assets/files/23473/datos_abiertos_2022_06.csv',
 '/site/assets/files/25235/datos_abiertos_2022_07.csv',
 '/site/assets/files/27484/datos_abiertos_2022_08.csv',
 '/site/assets/files/29663/datos_abiertos_2022_09.csv',
 '/site/assets/files/31507/datos_abiertos_2022_10.csv',
 '/site/assets/files/33115/datos_abiertos_2022_11.csv',
 '/site/assets/files/34432/datos_abiertos_2022_12.csv',
 '/site/assets/files/36762/datos_abiertos_2023_01.csv',
 '/site/assets/files/40197/datos_abiertos_2023_02.csv',
 '/site/assets/files/43035/datos_abiertos_2023_03.csv',
 '/site/assets/files/46758/datos_abiertos_2023_04.csv',
 '/site/assets/files/46759/datos_abiertos_2023_05.csv',
 '/site/assets/files/48116/datos_abiertos_2023_06.csv',
 '/site/assets/files/49448/datos_abiertos_2023_07.csv',
 '/site/assets/files/51295/datos_abiertos_2023_08.csv',
 '/site/assets/files/53344/datos_abiertos_2023_09.csv',
 '/site/assets/files/54935/datos_abiertos_2023_10.csv',
 '/site/assets/files/57344/datos_abiertos_2023_11.csv',
 '/site/assets/files/58715/datos_abiertos_2023_12.csv',
 '/site/assets/files/61450/datos_abiertos_2024_01.csv',
 '/site/assets/files/77251/datos_abiertos_2024_02.csv',
 '/site/assets/files/77252/datos_abiertos_2024_03.csv',
 '/site/assets/files/80028/datos_abiertos_2024_04.csv',
 '/site/assets/files/81663/datos_abiertos_2024_05.csv',
 '/site/assets/files/83901/datos_abiertos_2024_06.csv',
 '/site/assets/files/85500/datos_abiertos_2024_07.csv',
 '/site/assets/files/87665/datos_abiertos_2024_08.csv',
 '/site/assets/files/89736/datos_abiertos_2024_09.csv',
 '/site/assets/files/91758/datos_abiertos_2024_10.csv',
 '/site/assets/files/93516/datos_abiertos_2024_11.csv',
 '/site/assets/files/94962/datos_abiertos_2024_12.csv',
 '/site/assets/files/97653/datos_abiertos_2025_01.csv',
 '/site/assets/files/99879/datos_abiertos_2025_02.csv',
 '/site/assets/files/101986/datos_abiertos_2025_03.csv',
 '/site/assets/files/103813/datos_abiertos_2025_04.csv',
 '/site/assets/files/105513/datos_abiertos_2025_05.csv',
 '/site/assets/files/107088/datos_abiertos_2025_06.csv',
 '/site/assets/files/108898/datos_abiertos_2025_07.csv',
 '/site/assets/files/111021/datos_abiertos_2025_08.csv',
 '/site/assets/files/113216/datos_abiertos_2025_09.csv',
 '/site/assets/files/115104/datos_abiertos_2025_10.csv',
 '/site/assets/files/116773/datos_abiertos_2025_11.csv',
 '/site/assets/files/118153/datos_abiertos_2025_12.csv',
 '/site/assets/files/120163/datos_abiertos_2026_01.csv',
 '/site/assets/files/121761/datos_abiertos_2026_02.csv',
 '/site/assets/files/123236/datos_abiertos_2026_03.csv',
 '/site/assets/files/124927/datos_abiertos_2026_04.csv',
 '/site/assets/files/125943/datos_abiertos_2026_05.csv',
 '/site/assets/files/127734/datos_abiertos_2026_06.csv',
 '/site/assets/files/129006/datos_abiertos_2026_07.csv',
 '/site/assets/files/130362/datos_abiertos_2026_08.csv',
 '/site/assets/files/131825/datos_abiertos_2026_09.csv']

# Download a file

In [68]:
filepath = df_paths.loc[0, 'path']

file_url = base_url + filepath

file_url

'https://mibici.net/site/assets/files/1079/datos_abiertos_2014_12.csv'

In [69]:
r_file = requests.get(file_url, headers=headers)

r_file

In [76]:
type(r_file.content)

bytes

In [77]:
filename = filepath.split('/')[-1]
print(filename)

with open(filename, 'wb') as f:
    f.write(r_file.content)

datos_abiertos_2014_12.csv

# Read file

In [81]:
df = pandas.read_csv(filename)

df

,Viaje_Id,Usuario_Id,Genero,Año_de_nacimiento,Inicio_del_viaje,Fin_del_viaje,Origen_Id,Destino_Id
0,4601,10324,M,NaN,2014-12-01 00:33:47,2014-12-01 00:36:54,47,47
1,4604,10324,M,NaN,2014-12-01 01:06:54,2014-12-01 01:08:45,5,5
2,4628,3,F,1990.0,2014-12-01 09:47:20,2014-12-01 09:47:47,79,79
3,4631,102,M,1982.0,2014-12-01 09:48:23,2014-12-01 09:48:37,79,79
4,4632,3,F,1990.0,2014-12-01 09:48:46,2014-12-01 09:48:57,79,79
...,...,...,...,...,...,...,...,...
23962,42029,1736,M,1966.0,2014-12-31 22:43:35,2014-12-31 22:56:17,51,38
23963,42030,20342,M,NaN,2014-12-31 22:49:43,2014-12-31 23:04:32,77,50
23964,42031,20342,M,NaN,2014-12-31 23:09:37,2014-12-31 23:25:23,50,37
23965,42032,1736,M,1966.0,2014-12-31 23:33:28,2014-12-31 23:39:59,51,52
23966,42033,16054,M,1976.0,2014-12-31 23:38:57,2014-12-31 23:47:09,14,47

In [83]:
cols = list(df.columns)
cols

['Viaje_Id',
 'Usuario_Id',
 'Genero',
 'Año_de_nacimiento',
 'Inicio_del_viaje',
 'Fin_del_viaje',
 'Origen_Id',
 'Destino_Id']

In [87]:
for col in cols:
    col_lower = col.lower()
    col_norm = unicodedata.normalize('NFKD', col_lower)
    col_final = col_norm.encode('ascii', 'ignore').decode('ascii')

    print(col, '\n', col_norm, '\n', col_final)
    print('')

Viaje_Id
 viaje_id
 viaje_id

Usuario_Id
 usuario_id
 usuario_id

Genero
 genero
 genero

Año_de_nacimiento
 año_de_nacimiento
 ano_de_nacimiento

Inicio_del_viaje
 inicio_del_viaje
 inicio_del_viaje

Fin_del_viaje
 fin_del_viaje
 fin_del_viaje

Origen_Id
 origen_id
 origen_id

Destino_Id
 destino_id
 destino_id